import AppKit
import SwiftUI

/// Zero-size, hidden `NSView` used only to reach its `window` once attached, so the
/// accessibility bridges below can run after AppKit has actually created the native
/// controls they tag.
final class TaggingProbeView: NSView {
    var onWindowAvailable: ((NSWindow) -> Void)?

    override init(frame frameRect: NSRect) {
        super.init(frame: frameRect)
        isHidden = true
    }

    required init?(coder: NSCoder) {
        fatalError("TaggingProbeView does not support NSCoder")
    }

    override func viewDidMoveToWindow() {
        super.viewDidMoveToWindow()
        guard let window = self.window else { return }
        onWindowAvailable?(window)
    }
}

/// Invisible probe that finds the one live `NSSearchField` generated by `.searchable`
/// and tags its exposed accessibility element with `identifier`. See
/// ``AccessibilityBridge`` for why this can't be done with a plain SwiftUI modifier.
struct SearchFieldAccessibilityTag: NSViewRepresentable {
    let identifier: String

    func makeNSView(context: Context) -> TaggingProbeView {
        let probe = TaggingProbeView()
        let identifier = identifier
        probe.onWindowAvailable = { window in
            AccessibilityBridge.retry {
                guard let field = AccessibilityBridge.uniqueSearchField(in: window),
                      let element = AccessibilityBridge.exposedElement(for: field) else {
                    return false
                }
                AccessibilityBridge.tag(element, identifier: identifier)
                return true
            }
        }
        return probe
    }

    func updateNSView(_ nsView: TaggingProbeView, context: Context) {}
}

/// Invisible probe that tags one Settings-window tab segment — the `AXRadioButton`
/// child at `segmentIndex` of the one segmented control with `segmentCount` segments —
/// with `identifier`.
struct SegmentedTabAccessibilityTag: NSViewRepresentable {
    let identifier: String
    let segmentIndex: Int
    let segmentCount: Int

    func makeNSView(context: Context) -> TaggingProbeView {
        let probe = TaggingProbeView()
        let identifier = identifier
        let segmentIndex = segmentIndex
        let segmentCount = segmentCount
        probe.onWindowAvailable = { window in
            AccessibilityBridge.retry {
                guard let control = AccessibilityBridge.uniqueSegmentedControl(in: window, segmentCount: segmentCount),
                      let elements = AccessibilityBridge.segmentElements(of: control),
                      elements.indices.contains(segmentIndex) else {
                    return false
                }
                AccessibilityBridge.tag(elements[segmentIndex], identifier: identifier)
                return true
            }
        }
        return probe
    }

    func updateNSView(_ nsView: TaggingProbeView, context: Context) {}
}

/// Invisible probe that tags every inline theme-picker option — the native
/// `AXRadioButton`s SwiftUI renders for `.pickerStyle(.inline)`, in top-to-bottom order —
/// with `settings.theme.<id>`, in the exact order `themeIDs` lists.
struct ThemeOptionsAccessibilityTag: NSViewRepresentable {
    let themeIDs: [String]

    func makeNSView(context: Context) -> TaggingProbeView {
        let probe = TaggingProbeView()
        let themeIDs = themeIDs
        probe.onWindowAvailable = { window in
            AccessibilityBridge.retry {
                let buttons = AccessibilityBridge.orderedRadioButtons(in: window)
                guard buttons.count == themeIDs.count else { return false }
                for (button, id) in zip(buttons, themeIDs) {
                    AccessibilityBridge.tag(button, identifier: "settings.theme.\(id)")
                }
                return true
            }
        }
        return probe
    }

    func updateNSView(_ nsView: TaggingProbeView, context: Context) {}
}
