import AppKit

/// Low-level AppKit accessibility helpers used to tag a handful of native controls (the
/// sidebar's `.searchable` field, the Settings tab segments, and the inline theme
/// picker's radio buttons) with the stable, non-localized identifiers XCUITest needs.
///
/// Plain SwiftUI accessibility modifiers are enough for every other required identifier.
/// These three controls are generated by AppKit/SwiftUI bridging in a way that makes a
/// plain `.accessibilityIdentifier(...)` on the SwiftUI content either land on the wrong,
/// AX-ignored node or propagate to unrelated sibling elements (issue #37 repair
/// evidence), so this locates and tags the real, exposed accessibility element directly.
enum AccessibilityBridge {
    /// The accessibility element AppKit clients actually see for `view`: `view` itself
    /// when it is already an accessibility element, otherwise its nearest unignored
    /// descendant. `NSSearchField`, for example, is itself ignored — its real element is
    /// exposed on its cell.
    static func exposedElement(for view: NSView) -> NSAccessibilityProtocol? {
        NSAccessibility.unignoredDescendant(of: view) as? NSAccessibilityProtocol
    }

    /// Marks `element` as an accessibility element carrying the exact `identifier`.
    static func tag(_ element: NSAccessibilityProtocol, identifier: String) {
        element.setAccessibilityElement(true)
        element.setAccessibilityIdentifier(identifier)
    }

    /// Depth-first collection of every `NSView` of type `T` under (and including) `root`.
    static func collect<T: NSView>(_ type: T.Type, under root: NSView) -> [T] {
        var results: [T] = []
        if let match = root as? T {
            results.append(match)
        }
        for subview in root.subviews {
            results.append(contentsOf: collect(type, under: subview))
        }
        return results
    }

    /// The single `NSSearchField` live under `window`: checks both its normal content-
    /// tree location (a sidebar's split-view accessory) and the toolbar-item location
    /// some OS/placement combinations use instead, deduplicated by identity. Fails
    /// closed (returns nil) unless exactly one unique field exists.
    static func uniqueSearchField(in window: NSWindow) -> NSSearchField? {
        var byIdentity: [ObjectIdentifier: NSSearchField] = [:]

        if let contentView = window.contentView {
            for field in collect(NSSearchField.self, under: contentView) {
                byIdentity[ObjectIdentifier(field)] = field
            }
        }
        for item in window.toolbar?.items ?? [] {
            if let searchItem = item as? NSSearchToolbarItem {
                let field = searchItem.searchField
                byIdentity[ObjectIdentifier(field)] = field
            }
        }

        guard byIdentity.count == 1, let field = byIdentity.values.first else { return nil }
        return field
    }

    /// The single `NSSegmentedControl` under `window` with exactly `segmentCount`
    /// segments, checked in both the content tree and toolbar item views. Fails closed
    /// unless exactly one such control is found.
    static func uniqueSegmentedControl(in window: NSWindow, segmentCount: Int) -> NSSegmentedControl? {
        var candidates: [NSSegmentedControl] = []

        if let contentView = window.contentView {
            candidates.append(contentsOf: collect(NSSegmentedControl.self, under: contentView))
        }
        for item in window.toolbar?.items ?? [] {
            if let view = item.view {
                candidates.append(contentsOf: collect(NSSegmentedControl.self, under: view))
            }
        }

        let matches = candidates.filter { $0.segmentCount == segmentCount }
        guard matches.count == 1, let control = matches.first else { return nil }
        return control
    }

    /// The `AXRadioButton` accessibility children of `control`'s cell, exposed one per
    /// segment. Requires the child count to match `control.segmentCount`, failing closed
    /// otherwise.
    static func segmentElements(of control: NSSegmentedControl) -> [NSAccessibilityProtocol]? {
        guard let cell = control.cell as? NSAccessibilityProtocol else { return nil }
        let children = (cell.accessibilityChildren() ?? []).compactMap { $0 as? NSAccessibilityProtocol }
        guard children.count == control.segmentCount else { return nil }
        return children
    }

    /// Every native radio-button control under `window`'s content, in top-to-bottom
    /// visual order. AppKit's window coordinate space has its origin at the bottom-left,
    /// so an earlier (higher) row has the greater y. Used to tag the inline theme
    /// picker's options, which SwiftUI renders as real `NSButton`s with a radio-role cell.
    static func orderedRadioButtons(in window: NSWindow) -> [NSAccessibilityProtocol] {
        guard let contentView = window.contentView else { return [] }
        let buttons: [(button: NSButton, element: NSAccessibilityProtocol)] = collect(NSButton.self, under: contentView)
            .compactMap { button in
                guard let cell = button.cell as? NSAccessibilityProtocol, cell.accessibilityRole() == .radioButton else {
                    return nil
                }
                return (button, cell)
            }

        return buttons
            .sorted { $0.button.convert(NSPoint.zero, to: nil).y > $1.button.convert(NSPoint.zero, to: nil).y }
            .map(\.element)
    }

    /// Retries `attempt` on the main queue with a short delay until it returns `true` or
    /// the bounded attempt budget is exhausted. Native controls can appear a beat after
    /// the SwiftUI/AppKit bridging layer's synchronous update/layout callbacks, so a
    /// single immediate attempt is not reliable — but this must not become an unbounded,
    /// silent no-op if a control never appears.
    static func retry(maxAttempts: Int = 40, interval: TimeInterval = 0.05, attempt: @escaping () -> Bool) {
        if attempt() { return }
        guard maxAttempts > 1 else { return }
        DispatchQueue.main.asyncAfter(deadline: .now() + interval) {
            retry(maxAttempts: maxAttempts - 1, interval: interval, attempt: attempt)
        }
    }
}
