import AppKit
import SwiftUI
import TickrCore

@main
struct TickrApp: App {
    @State private var sidebar: SidebarViewModel
    @State private var search: SymbolSearchViewModel
    @State private var selection: SidebarViewModel.Row.ID?
    @State private var themeStore: ThemeStore
    @State private var apiKeyStore: APIKeyStore

    // In production these route between live Finnhub/Yahoo and the offline mocks based on
    // the key in `apiKeyStore`, re-checked per request so entering a key in Settings takes
    // effect immediately (no restart). Under `--ui-testing` they are the forced mocks.
    private let quoteProvider: QuoteProvider
    private let candleProvider: CandleProvider

    init() {
        // Detect the launch mode and choose the whole dependency graph up-front, so a
        // `--ui-testing` launch is fully isolated (forced mocks, in-memory secret store,
        // isolated theme defaults, fresh empty favorites) and a normal launch is unchanged.
        // One favorites store is shared by the sidebar and search so adding a result
        // updates both.
        let deps = AppDependencies.make(launchMode: LaunchMode(arguments: CommandLine.arguments))
        _apiKeyStore = State(initialValue: deps.apiKeyStore)
        _themeStore = State(initialValue: deps.themeStore)

        self.quoteProvider = deps.quoteProvider
        self.candleProvider = deps.candleProvider
        _sidebar = State(initialValue: SidebarViewModel(store: deps.favoritesStore, provider: deps.quoteProvider))
        _search = State(initialValue: SymbolSearchViewModel(
            provider: deps.searchProvider,
            store: deps.favoritesStore
        ))
    }

    var body: some Scene {
        WindowGroup {
            NavigationSplitView {
                SidebarView(model: sidebar, search: search, selection: $selection)
            } detail: {
                if let symbol = selection {
                    DetailView(model: DetailViewModel(
                        symbol: symbol,
                        quoteProvider: quoteProvider,
                        candleProvider: candleProvider
                    ))
                    // Rebuild the detail (and its view model) when the selection changes.
                    .id(symbol)
                } else {
                    DetailPlaceholderView()
                }
            }
            .frame(minWidth: 640, minHeight: 420)
            // A single selection recolors the whole tree: inject the active theme and
            // drive the app-wide accent from it.
            .environment(\.theme, themeStore.selected)
            .tint(themeStore.selected.accent)
        }
        .defaultSize(width: 900, height: 600)

        Settings {
            TabView {
                APIKeySettingsView(store: apiKeyStore)
                    .tabItem { Label("Data", systemImage: "key") }
                ThemeSettingsView(store: themeStore)
                    .tabItem { Label("Appearance", systemImage: "paintbrush") }
            }
            // A native Settings TabView is backed by an NSSegmentedControl. SwiftUI's
            // view-level identifier modifiers stay on tab content/labels and do not reach
            // the control's actionable accessibility segments, so tag those public AppKit
            // accessibility elements without replacing the native tab UI.
            .background(SettingsTabIdentifierBridge(identifiers: [
                "settings.dataTab",
                "settings.appearanceTab",
            ]))
        }
    }
}

/// Tags the actionable radio-button segments generated by the native Settings `TabView`.
/// The identifier order mirrors the `TabView` declaration above; UI tests never depend on
/// element indexes, labels, or localized strings.
private struct SettingsTabIdentifierBridge: NSViewRepresentable {
    let identifiers: [String]

    func makeNSView(context: Context) -> TaggingView {
        TaggingView(identifiers: identifiers)
    }

    func updateNSView(_ nsView: TaggingView, context: Context) {
        nsView.identifiers = identifiers
        nsView.tagSegmentsIfAvailable()
    }

    final class TaggingView: NSView {
        var identifiers: [String]

        init(identifiers: [String]) {
            self.identifiers = identifiers
            super.init(frame: .zero)
            setAccessibilityElement(false)
        }

        required init?(coder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }

        deinit {
            NotificationCenter.default.removeObserver(self)
        }

        override func viewDidMoveToWindow() {
            super.viewDidMoveToWindow()
            NotificationCenter.default.removeObserver(self)
            guard let window else { return }

            NotificationCenter.default.addObserver(
                self,
                selector: #selector(windowDidUpdate),
                name: NSWindow.didUpdateNotification,
                object: window
            )
            NotificationCenter.default.addObserver(
                self,
                selector: #selector(toolbarWillAddItem),
                name: NSToolbar.willAddItemNotification,
                object: nil
            )
            tagSegmentsIfAvailable()
            DispatchQueue.main.async { [weak self] in self?.tagSegmentsIfAvailable() }
        }

        @objc private func windowDidUpdate(_ notification: Notification) {
            tagSegmentsIfAvailable()
        }

        @objc private func toolbarWillAddItem(_ notification: Notification) {
            DispatchQueue.main.async { [weak self] in self?.tagSegmentsIfAvailable() }
        }

        func tagSegmentsIfAvailable() {
            guard let window else { return }
            let toolbarRoots = window.toolbar?.items.compactMap(\.view) ?? []
            let contentRoots = window.contentView.map { [$0] } ?? []
            let controls = (toolbarRoots + contentRoots)
                .flatMap(Self.segmentedControls(in:))
                .filter { $0.segmentCount == identifiers.count }
            guard controls.count == 1,
                  let children = controls[0].cell?.accessibilityChildren()
            else { return }

            let segments = children.compactMap { $0 as? NSAccessibilityProtocol }
            guard segments.count == identifiers.count else { return }
            for (segment, identifier) in zip(segments, identifiers) {
                segment.setAccessibilityIdentifier(identifier)
            }
        }

        private static func segmentedControls(in view: NSView) -> [NSSegmentedControl] {
            let current = (view as? NSSegmentedControl).map { [$0] } ?? []
            return current + view.subviews.flatMap(segmentedControls(in:))
        }
    }
}
